<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="UserStatusDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=9b40ce93-2d72-42d9-a4c1-a0f6015a9d04.sqlserver.sequelizer.com;User ID=ophsjzldiglbranl;Password=q6ZrNmhv2YUCscZJMSHMq2ceE7nTS63MdfYRaw4wA6ZFj5Wrw2x5y2kx3VUP7wL5" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserStatus" Member="UserStatus">
    <Type Name="UserStatus">
      <Column Name="UserHash" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>